# Generated by Django 4.0.4 on 2022-05-08 18:46

import django.core.validators
from django.db import migrations, models
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='src',
            field=models.ImageField(upload_to=photos.models.nameFile, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])]),
        ),
    ]
