# Generated by Django 4.0.4 on 2022-05-08 18:46

import about.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profile', models.ImageField(upload_to=about.models.nameFile, validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png'])])),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField()),
            ],
        ),
    ]
