# Generated by Django 4.0.4 on 2022-05-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactfield',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
